### ISSUE TITLE
"Main"-Teile in main-Funktion

### ISSUE THREAD

**Issue by penguineer** [maz3max/ble-spaceauth-manager#1]
https://github.com/maz3max/ble-spaceauth-manager/blob/6f1cfad7b20b0eb2834afcf8204f788d9868ec3d/ble-spaceauth-manager.py#L179

Bitte diesen Teil in eine "main"-Funktion auslagern, die dann direkt aufgerufen wird. Ansonsten sind alle hier deklarierten Variablen global.

**Comment by maz3max** [comment]
Wurde umgesetzt. Nur globale Dinge sind noch im main-Teil außerhalb der main-Funktion.
